
name: 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '25 12 * * 4'
  workflow_dispatch:

jobs:
  xanitizer-security-analysis:
    # Xanitizer runs on and windows-latest.
    runs-on: windows-latest

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Uploads the findings into the GitHub code scanning alert section using the upload-sarif action
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports
