# This workflow integrates Scan with GitHub's code scanning feature
# Scan is a free open-source security tool for modern DevOps teams from ShiftLeft
# Visit https://slscan.io/en/latest/integrations/code-scan for help
name: 

on:
  push:
    branches: [ main ]
  schedule:
    - Monday 3:55 AM

jobs:* 1'


    runs-on: ubuntu-lates
